version: '3.5'
services:

  forms-fe:
    container_name: forms-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - forms-network
    stdin_open: true
      
networks:
  forms-network:
    external:
      name: forms-network      
  
        