version: '3'
services:

  form-fe: 
    image: forms-fe
    ports:
      - "3000:3000"
    # volumes:
      # - '.:/app'
      # - '/app/node_modules'
    networks:
      - forms-network
    depends_on:
      - forms-be
    stdin_open: true
      
  forms-be:
    image: andreyley/forms-be:1.0.0
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    ports:
      - "5050:80"
    links:
      - "mongo"
    networks:
      - forms-network
    depends_on:
      - mongo
    restart: always
    
  mongo:
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example    
    ports:
      - "5060:27017"
    networks:
      - forms-network

      
networks:
  forms-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24        
  
        